packages:
  - name: lambda
    actions:
      - name: 'mnemonix'
        runtime: 'go:1.20'
        limits:
          timeout: 1000
          memory: 128
      - name: 'wallet'
        runtime: 'go:1.20'
        limits:
          timeout: 3500
          memory: 128
